name: Weekly Game Health Check

on:
  schedule:
    # Every Monday at 3:00 AM UTC (11:00 PM Eastern Sunday)
    - cron: '0 3 * * 1'
  workflow_dispatch: # Allow manual trigger

env:
  FAILURE_THRESHOLD: 3 # Auto-disable after 3 consecutive failures

jobs:
  health-check:
    name: Game Availability Health Check
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
        
    - name: Install dependencies
      run: |
        pip install requests
        
    - name: Run game health check
      run: |
        python scripts/check_games.py
        
    - name: Check for inactive games and update data
      run: |
        python scripts/auto_disable_games.py
        
    - name: Generate health report
      run: |
        python scripts/generate_health_report.py > health_report.md
        
    - name: Commit changes if any games were disabled
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        
        # Check if there are changes to commit
        if [ -n "$(git status --porcelain)" ]; then
          echo "Games data updated - committing changes"
          git add data/games.json data/inactive_games.json scripts/results/
          git commit -m "🤖 Weekly health check: Auto-disable failed games

          $(cat health_report.md)
          
          🤖 Generated with [Claude Code](https://claude.ai/code)
          
          Co-Authored-By: Claude <noreply@anthropic.com>"
          git push
        else
          echo "No changes detected - all games healthy"
        fi
        
    - name: Upload health report artifact
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: health-report-${{ github.run_number }}
        path: |
          health_report.md
          scripts/results/
          
    - name: Send notification on failures
      if: failure()
      run: |
        echo "Health check failed - manual investigation required"
        echo "Check the logs and inactive games list"
        
  notify-results:
    name: Send Health Check Results
    needs: health-check
    runs-on: ubuntu-latest
    if: always()
    
    steps:
    - name: Download artifacts
      uses: actions/download-artifact@v4
      with:
        name: health-report-${{ github.run_number }}
        
    - name: Display summary
      run: |
        echo "=== WEEKLY GAME HEALTH CHECK SUMMARY ==="
        echo "Date: $(date)"
        echo "Status: ${{ needs.health-check.result }}"
        echo ""
        if [ -f "health_report.md" ]; then
          cat health_report.md
        else
          echo "No health report generated"
        fi
        echo ""
        echo "View full details: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"